# Generated by Django 6.0.5 on 2026-05-14 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('devEUI', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing')], default='passing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCnt', models.IntegerField()),
                ('data', models.CharField(max_length=512)),
                ('rxInfo', models.JSONField()),
                ('txInfo', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devEUI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexmodal.device')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('devEUI', 'fCnt'), name='unique_payload_per_device')],
            },
        ),
    ]
