# Generated by Django 6.0.5 on 2026-05-14 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing')], default='passing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('fCnt', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.TextField()),
                ('rxInfo', models.JSONField()),
                ('txInfo', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deviceEUI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexmodal.device')),
            ],
        ),
    ]
