# Generated by Django 6.0.5 on 2026-05-14 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexmodal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devEUI',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='DevEUI must be exactly 16 hexadecimal characters.', regex='^[0-9a-fA-F]{16}$')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing')], max_length=20),
        ),
    ]
