# Generated by Django 6.0.5 on 2026-05-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexmodal', '0002_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='data',
            field=models.CharField(max_length=512),
        ),
    ]
